### ISSUE TITLE
Issue when using riot.js tag in content

### ISSUE THREAD

**Issue by amitguptagwl** [craftpip/jquery-confirm#409]
**jquery-confirm version:**
v3.3.2

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x] support request

**Current behavior:**

I'm not able to use riot.js tag in content.

```
jQuery.Deferred exception: Cannot read property 'class' of undefined TypeError: Cannot read property 'class' of undefined
    at xt (http://127.0.0.1:8080/js/thirdparty/riot+compiler.min.js:2:24322)
    at e (http://127.0.0.1:8080/js/thirdparty/riot+compiler.min.js:2:15556)
    at me (http://127.0.0.1:8080/js/thirdparty/riot+compiler.min.js:2:9810)
    at e (http://127.0.0.1:8080/js/thirdparty/riot+compiler.min.js:2:15618)
    at Object.Je [as mount] (http://127.0.0.1:8080/js/thirdparty/riot+compiler.min.js:2:15626)
    at http://127.0.0.1:8080/js/thirdparty/riot+compiler.min.js:2:36481
    at Sr (http://127.0.0.1:8080/js/thirdparty/riot+compiler.min.js:2:35978)
    at Object.mount (http://127.0.0.1:8080/js/thirdparty/riot+compiler.min.js:2:36462)
    at Jconfirm.onContentReady (http://127.0.0.1:8080/js/settings.js:15:18)
    at Array.<anonymous> (http://127.0.0.1:8080/js/thirdparty/jquery-confirm.min.js:11:6263) undefined
```

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
```js
$.dialog({
        title : 'Settings',
        content : '<settings-window></settings-window>',
        escapeKey: true,
        backgroundDismiss: true,
        onContentReady: function(){
            riot.mount('settings-window');
        }
    })
```

**Other information:**

**Comment by amitguptagwl** [comment]
It was my bad. I missed to include the tag file on the page.
